id: P4915B721
initial_creation_type: input
source_metadata:
  title: Tenth Paṇchen Lama Series
  language: en
  description: 'Texts by and about the Tenth Paṇchen Lama, Trinlé Lhundrup Chökyi
    Gyaltsen (phrin las lhun grub chos kyi rgyal mtshan, 1938–1989):'
  volume:
    ec52b34e53874556b62c6e82fd7aa963:
      title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the
        All-Knowing Paṇchen Rinpoche of Tsang'
      parent: Long Life Prayers
created_at: '2022-03-01T01:40:38.719309'
last_modified_at: '2022-03-01T01:40:38.719315'
